### ISSUE TITLE
Style sheet could not be opened

### ISSUE THREAD

**Issue by plane007** [apostrophecms/apostrophe-boilerplate#7]
Using the code from the tutorial to create default.html, a boilerplate page is created. However, the pages is not presented correctly in the browser. The hero and hero-text classes do not seem to be defined.
(http://mapworldlive.com:3000/new-page - a development system when app.js is running)

The developer tools in Firefox report that a style sheet could not be loaded:
/modules/apostrophe-assets/css/vendor/pikaday.less

In searching the software, I find the file is actually in:
./node_modules/apostrophe/lib/modules/apostrophe-assets/public/css/vendor/pikaday.less

Strangely, Chrome developer tools do not report this.

**Comment by stuartromanek** [comment]
I'm getting a 404 on your link, and your homepage seems to be loading assets correctly in FF and Chrome.

Have you got this resolved @plane007 ?

**Comment by plane007** [comment]
You got a 404 because I have reset the site. In recreating the page (which is now available), I seem to have removed the error message. However, I note that I can no longer find the class.

**Comment by plane007** [comment]
Thanks for your attentiom

**Comment by stuartromanek** [comment]
You should be able to work in your `/lib/modules/apostrophe-assets/public/css/site.less` file for front-end styles now.

When you confirm everything is working please close this issue, thanks for checking out Apostrophe @plane007 !
